-- VisaShot Supabase schema.
-- Run once against a fresh Supabase Postgres project (SQL editor or `supabase db push`).
--
-- Design notes:
--   * No user accounts — orders are looked up by nanoid id (never sequential).
--   * RLS is default-deny; only the service-role key (server-only) touches this
--     table directly, so there are no public policies at all — the deny-all
--     default IS the policy. A test should confirm the anon key cannot read
--     any row.
--   * specs are mirrored here for analytics only; data/photo-specs.ts remains
--     the source of truth for processing.

create extension if not exists "pgcrypto";

create table if not exists orders (
  id text primary key, -- nanoid, generated by the app
  email text,
  spec_id text not null,
  addon_spec_ids text[] not null default '{}',
  original_path text,
  processed_path text,
  watermarked_path text,
  print_sheet_path text,
  stripe_session_id text,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'delivered', 'refunded')),
  compliance_report jsonb,
  amount_cents integer not null default 0,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  recovery_email_sent boolean not null default false,
  doc_expiry date,
  expiry_reminder_6mo_sent boolean not null default false,
  expiry_reminder_1mo_sent boolean not null default false
);

create index if not exists orders_status_idx on orders (status);
create index if not exists orders_stripe_session_idx on orders (stripe_session_id);
create index if not exists orders_created_at_idx on orders (created_at);
create index if not exists orders_recovery_idx on orders (status, recovery_email_sent, email);

alter table orders enable row level security;
-- No policies created: RLS default-deny means only the service-role key
-- (which bypasses RLS entirely, per Supabase semantics) can read/write.
-- Verify with a test: an anon-key client must get zero rows from this table.

create table if not exists specs_mirror (
  id text primary key,
  country text not null,
  country_code text not null,
  doc_type text not null,
  display_name text not null,
  updated_at timestamptz not null default now()
);

alter table specs_mirror enable row level security;
-- Read-only reference data — safe to expose publicly if ever needed, but kept
-- deny-by-default until a concrete anonymous read use case exists.

-- Storage: create a PRIVATE bucket named "visashot" via the dashboard or:
--   insert into storage.buckets (id, name, public) values ('visashot', 'visashot', false)
--   on conflict (id) do nothing;
-- Then add a lifecycle/expiration rule (Dashboard → Storage → Policies) or rely
-- on the /api/cron/purge job, which is authoritative either way.
